- name: Creating install directory
  file: path={{ item.path }} state=directory mode={{ item.mode }}
  with_items:
          - { path: "{{ zookeeper_install_dir }}", mode: '0755' }

- name: Populating and copying templates
  template: src={{ item.src }} dest="{{ zookeeper_install_dir}}/{{ item.dest }}" mode=0744
  with_items:
          - { src: 'zookeeper-config.sh.j2', dest: 'zookeeper-config.sh' }

- name: Copying configuration and scripts
  copy: src={{ item.file }} dest="{{ zookeeper_install_dir }}/{{ item.file }}"  mode={{ item.mode }}
  with_items:
          - { file: 'zoo.cfg', mode: '0644' }

- name: Creating the hadoop group
  group: name=hadoop state=present gid=2000

- name: Creating the zookeeper group
  group: name=zookeeper state=present gid=2003

- name: Creating the zookeeper user
  user: name=zookeeper uid=2003 groups=zookeeper,hadoop
