---
- name: Stopping zookeeper from any previous runs
  shell: "{{ zookeeper_install_dir }}/bin/zkServer.sh stop"
  ignore_errors: yes

- name: Cleaning up install directory from previous run
  file: path={{ zookeeper_install_dir }} state=absent 

- name: Creating install directory
  file: path={{ zookeeper_install_dir }} state=directory recurse=yes

- name: Extract zookeeper to install dir
  shell: "tar -zxvf {{ zookeeper_archive }} -C {{ zookeeper_install_dir }} --strip-components=1"

- name: Adding zookeeper bin dir to PATH
  shell: "echo \"export PATH=\$PATH:{{ zookeeper_install_dir }}/bin\" >> /etc/profile"

- name: Populating and copying configuration
  template: src={{ item.src }} dest="{{ zookeeper_install_dir}}/conf/{{ item.dest }}" mode=0744
  with_items:
          - { src: 'zoo.cfg.j2', dest: 'zoo.cfg' }

- name: Creating the hadoop group
  group: name=hadoop state=present gid=2000

- name: Creating the zookeeper group
  group: name=zookeeper state=present gid=2003

- name: Creating the zookeeper user
  user: name=zookeeper uid=2003 groups=zookeeper,hadoop

- name: Starting zookeeper
  shell: "{{ zookeeper_install_dir }}/bin/zkServer.sh start"
