---
- name: Creating install directory
  file: path={{ item.path }} state=directory mode={{ item.mode }}
  with_items:
          - { path: "{{ zookeeper_install_dir }}", mode: '0755' }

- name: Extract zookeeper to install dir
  shell: "tar -zxvf {{ zookeeper_archive }} -C {{ zookeeper_install_dir }} --strip-components=1"

- name: Populating and copying templates
  template: src={{ item.src }} dest="{{ zookeeper_install_dir}}/{{ item.dest }}" mode=0744
  with_items:
          - { src: 'zookeeper-config.sh.j2', dest: 'zookeeper-config.sh' }
          - { src: 'provision-zookeeper.sh.j2', dest: 'provision-zookeeper.sh' }
          - { src: 'zoo.cfg.j2', dest: 'zoo.cfg' }

- name: Creating the hadoop group
  group: name=hadoop state=present gid=2000

- name: Creating the zookeeper group
  group: name=zookeeper state=present gid=2003

- name: Creating the zookeeper user
  user: name=zookeeper uid=2003 groups=zookeeper,hadoop
